<?php
declare(strict_types=1);

/* ───────────────────────────────────────────────
   config.php — everything install-specific lives here.

   Do not edit this file: drop a config.local.php next to it (it is
   git-ignored) and define the constants there. Whatever it defines
   wins; whatever it leaves out falls back to the defaults below.
   ─────────────────────────────────────────────── */

if (is_file(__DIR__ . '/config.local.php')) require __DIR__ . '/config.local.php';

/* Root of the editable tree. Nothing above it can be read or written.
   Default: the folder that contains koder/ — usually your web root.
   Point it higher only if you understand what that opens up. */
defined('KODER_BASE') || define('KODER_BASE', dirname(__DIR__));

/* Password hash, sessions, rate-limit counters, approval requests.
   Keep this OUTSIDE the web root. Keeping it outside KODER_BASE too is
   stronger still: then koder cannot rewrite its own credentials. */
defined('KODER_DATA') || define('KODER_DATA', dirname(__DIR__, 2) . '/koder-data');

/* Public origin of the site you are editing, used by the preview to
   fetch a page over HTTP. It is NOT derived from the request, because
   koder may be served from a different host than the site it edits
   (koder.example.com editing example.com). */
defined('KODER_SITE') || define('KODER_SITE', 'https://' . basename(KODER_BASE));

/* Second factor: after the password, a login waits for an approval that
   has to come from somewhere koder cannot reach. OFF by default — with
   nothing on the other side to approve, turning it on locks you out.
   Read the "Two-factor approval" section of the README first. */
defined('KODER_2FA') || define('KODER_2FA', false);
