<?php
declare(strict_types=1);

/* ───────────────────────────────────────────────
   config.php — the only two paths koder needs.

   Do not edit this file: drop a config.local.php next to it
   (git-ignores it) and define the constants there. Whatever it
   defines wins; whatever it leaves out falls back to the
   defaults below.
   ─────────────────────────────────────────────── */

if (is_file(__DIR__ . '/config.local.php')) require __DIR__ . '/config.local.php';

/* Root of the editable tree. Nothing above it can be read or written.
   Default: the folder that contains koder/ — usually your web root.
   Point it higher only if you understand what that opens up. */
defined('KODER_BASE') || define('KODER_BASE', dirname(__DIR__));

/* Password hash + PHP session files.
   Keep this OUTSIDE the web root and outside KODER_BASE: if koder can
   edit it, anyone inside koder can delete the password and walk in. */
defined('KODER_DATA') || define('KODER_DATA', dirname(__DIR__, 2) . '/koder-data');
